name: ci-sonnar
on: 
  pull_request:
    branches:
      - develop
jobs:
  ci-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -converprofile=coverage.out

    